from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    app_name: str = "Quantitative Trading System"
    trade_mode: str = "paper"
    default_cash: float = 1_000_000.0
    timezone: str = "Asia/Shanghai"
    market_open_buy_time: str = "09:31"
    scheduled_close_time: str = "14:55"
    data_provider: str = "akshare"
    cache_dir: str = "data/cache"
    market_data_file_cache_enabled: bool = False
    database_path: str = "data/quant_system.db"
    database_url: str | None = None
    database_backend: str = "sqlite"
    environment: str = "local"
    allow_live_trading: bool = False
    allow_manual_open: bool = True
    allow_manual_close: bool = True
    allow_auto_buy: bool = False
    allow_auto_close: bool = True
    max_order_amount: float = 20_000.0
    max_daily_buy_amount: float = 100_000.0
    max_position_amount: float = 100_000.0
    auto_trade_pools: list[str] = ["favorites", "candidates"]
    auto_trade_quantity: int = 100
    auto_trade_max_positions: int = 5
    auto_trade_max_price: float = 200.0
    auto_trade_min_confidence: float = 0.58
    auto_trade_min_trend_score: float = 62.0
    auto_trade_max_volatility: float = 0.055
    auto_trade_min_price_position: float = 0.35
    auto_trade_max_price_position: float = 0.88
    auto_trade_min_volume_ratio: float = 0.75
    auto_trade_take_profit_pct: float = 0.08
    auto_trade_stop_loss_pct: float = 0.04
    paper_broker_backend: str = "sqlite"
    paper_slippage_bps: float = 5.0
    paper_commission_rate: float = 0.0003
    paper_min_commission: float = 5.0
    paper_stamp_duty_rate: float = 0.001
    paper_transfer_fee_rate: float = 0.00001
    redis_enabled: bool = False
    redis_url: str = "redis://localhost:6379/0"
    redis_socket_timeout_seconds: float = 1.0
    kline_cache_ttl_seconds: int = 3600
    kline_cache_prefix: str = "quant_system"
    news_cache_enabled: bool = True
    news_cache_ttl_seconds: int = 900
    news_cache_prefix: str = "quant_system"
    backtest_cache_enabled: bool = True
    backtest_cache_ttl_seconds: int = 7200
    backtest_cache_prefix: str = "quant_system"
    dashboard_cache_enabled: bool = True
    dashboard_cache_ttl_seconds: int = 120
    dashboard_cache_prewarm_on_startup: bool = True
    kline_sync_retry_count: int = 2
    kline_sync_retry_delay_seconds: float = 0.8
    kline_sync_min_rows: int = 20
    kline_sync_batch_size: int = 10
    kline_sync_symbol_pause_seconds: float = 0.6
    kline_sync_batch_pause_seconds: float = 2.5
    eastmoney_retry_count: int = 3
    eastmoney_retry_delay_seconds: float = 1.0
    eastmoney_connect_timeout_seconds: float = 10.0
    eastmoney_read_timeout_seconds: float = 20.0
    ai_enabled: bool = True
    ai_mock_enabled: bool = True
    ai_prompt_version: str = "v3"
    ai_context_kline_limit: int = 30
    ai_context_news_limit: int = 10
    ai_max_prompt_chars: int = 24000
    ai_max_rag_context_chars: int = 6000
    ai_max_rag_citations: int = 5
    llm_provider: str = "openai_compatible"
    llm_base_url: str | None = None
    llm_api_key: str | None = None
    llm_model: str = "deepseek-chat"
    llm_temperature: float = 0.2
    llm_timeout_seconds: float = 30.0
    llm_retry_count: int = 2
    llm_retry_delay_seconds: float = 1.0
    rag_enabled: bool = False
    rag_vector_backend: str = "qdrant"
    rag_qdrant_url: str = "http://localhost:6333"
    rag_qdrant_api_key: str | None = None
    rag_collection_news: str = "market_news_chunks"
    rag_embedding_provider: str = "openai_compatible"
    rag_embedding_model: str = "text-embedding-3-small"
    rag_embedding_base_url: str | None = None
    rag_embedding_api_key: str | None = None
    rag_embedding_dimension: int = 1536
    rag_embedding_batch_size: int = 10
    rag_embedding_retry_count: int = 2
    rag_embedding_retry_delay_seconds: float = 1.0
    rag_chunk_size: int = 800
    rag_chunk_overlap: int = 120
    rag_search_limit: int = 8
    rag_score_threshold: float | None = None
    rag_skip_embedding_if_pending_over: int = 0
    rag_news_days: int = 14

    model_config = SettingsConfigDict(env_file=".env", env_prefix="QUANT_")


settings = Settings()
