-- MySQL schema for quantitative_trad
-- Charset: utf8mb4
-- Collation: utf8mb4_unicode_ci

CREATE DATABASE IF NOT EXISTS quantitative_trad
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE quantitative_trad;

CREATE TABLE IF NOT EXISTS stock_basic (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  ts_code VARCHAR(32) NOT NULL COMMENT 'Tushare 股票代码，例如 600487.SH',
  symbol VARCHAR(16) NOT NULL COMMENT '纯数字股票代码，例如 600487',
  name VARCHAR(128) NOT NULL COMMENT '股票名称',
  area VARCHAR(64) NULL COMMENT '地区',
  industry VARCHAR(128) NULL COMMENT '行业',
  market VARCHAR(64) NULL COMMENT '市场板块，例如 主板/创业板/科创板/北交所',
  exchange VARCHAR(16) NULL COMMENT '交易所 SH/SZ/BJ',
  list_date VARCHAR(32) NULL COMMENT '上市日期 YYYYMMDD',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否活跃上市',
  source VARCHAR(64) NOT NULL DEFAULT 'tushare' COMMENT '数据来源',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  UNIQUE KEY uq_stock_basic_ts_code (ts_code),
  KEY idx_stock_basic_symbol (symbol),
  KEY idx_stock_basic_name (name),
  KEY idx_stock_basic_exchange (exchange),
  KEY idx_stock_basic_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股股票基础信息表';

CREATE TABLE IF NOT EXISTS stock_pools (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  code VARCHAR(64) NOT NULL COMMENT '股票池 code，例如 favorites/candidates/watchlist/blacklist/themes',
  name VARCHAR(128) NOT NULL COMMENT '股票池名称',
  description TEXT NULL COMMENT '股票池说明',
  pool_type VARCHAR(32) NOT NULL COMMENT '股票池类型，例如 manual/strategy/risk/theme',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  UNIQUE KEY uq_stock_pools_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='股票池定义表';

CREATE TABLE IF NOT EXISTS stock_pool_members (
  id INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  pool_code VARCHAR(64) NOT NULL COMMENT '股票池 code',
  symbol VARCHAR(32) NOT NULL COMMENT '股票代码',
  name VARCHAR(128) NULL COMMENT '股票名称',
  reason TEXT NULL COMMENT '入池原因',
  tags TEXT NULL COMMENT '标签 JSON 字符串',
  source VARCHAR(64) NOT NULL DEFAULT 'manual' COMMENT '来源，例如 manual/strategy/import',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  UNIQUE KEY uq_stock_pool_member (pool_code, symbol),
  KEY idx_stock_pool_members_pool_code (pool_code),
  KEY idx_stock_pool_members_symbol (symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='股票池成员表';

CREATE TABLE IF NOT EXISTS stock_klines (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  symbol VARCHAR(32) NOT NULL COMMENT '股票代码',
  period VARCHAR(32) NOT NULL COMMENT 'K 线周期，例如 daily/minute',
  trade_time VARCHAR(64) NOT NULL COMMENT '交易日期或交易时间',
  `open` DOUBLE NULL COMMENT '开盘价',
  high DOUBLE NULL COMMENT '最高价',
  low DOUBLE NULL COMMENT '最低价',
  `close` DOUBLE NULL COMMENT '收盘价',
  volume DOUBLE NULL COMMENT '成交量',
  amount DOUBLE NULL COMMENT '成交额',
  change_pct DOUBLE NULL COMMENT '涨跌幅',
  turnover_rate DOUBLE NULL COMMENT '换手率',
  source VARCHAR(64) NOT NULL DEFAULT 'akshare' COMMENT '数据来源',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  UNIQUE KEY uq_stock_kline (symbol, period, trade_time),
  KEY idx_stock_klines_symbol (symbol),
  KEY idx_stock_klines_period (period),
  KEY idx_stock_klines_trade_time (trade_time),
  KEY idx_stock_klines_symbol_period (symbol, period),
  KEY idx_stock_klines_symbol_period_time (symbol, period, trade_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='股票 K 线数据表';

CREATE TABLE IF NOT EXISTS kline_sync_logs (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  pool_code VARCHAR(64) NULL COMMENT '同步来源股票池 code',
  symbol VARCHAR(32) NULL COMMENT '股票代码',
  period VARCHAR(32) NOT NULL COMMENT 'K 线周期',
  status VARCHAR(32) NOT NULL COMMENT '同步状态 success/failed',
  rows_count INT NOT NULL DEFAULT 0 COMMENT '同步行数',
  message TEXT NULL COMMENT '同步信息或错误信息',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  KEY idx_kline_sync_logs_symbol (symbol),
  KEY idx_kline_sync_logs_pool_code (pool_code),
  KEY idx_kline_sync_logs_status (status),
  KEY idx_kline_sync_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='K 线同步日志表';

CREATE TABLE IF NOT EXISTS market_news (
  id INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  news_id VARCHAR(128) NOT NULL COMMENT '资讯唯一 ID，默认取 fingerprint 前 32 位',
  fingerprint VARCHAR(128) NOT NULL COMMENT '去重指纹：source + news_type + title + published_at + url',
  title VARCHAR(512) NOT NULL COMMENT '资讯标题',
  summary TEXT NULL COMMENT '摘要',
  content TEXT NULL COMMENT '正文内容',
  url TEXT NULL COMMENT '原文链接',
  source VARCHAR(64) NOT NULL COMMENT '来源，例如 eastmoney-akshare/akshare-notice',
  news_type VARCHAR(32) NOT NULL COMMENT '资讯类型 news/notice',
  published_at VARCHAR(64) NOT NULL COMMENT '发布时间 ISO 字符串或来源原始时间字符串',
  fetched_at VARCHAR(64) NOT NULL COMMENT '抓取入库时间 ISO 字符串',
  related_symbols TEXT NULL COMMENT '关联股票代码 JSON 数组字符串',
  related_sectors TEXT NULL COMMENT '关联板块 JSON 数组字符串',
  tags TEXT NULL COMMENT '标签 JSON 数组字符串',
  sentiment VARCHAR(32) NULL COMMENT '情绪标签，预留字段',
  importance DOUBLE NULL COMMENT '重要性分数，预留字段',
  raw_json TEXT NULL COMMENT '来源原始记录 JSON',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  UNIQUE KEY uq_market_news_fingerprint (fingerprint),
  UNIQUE KEY uq_market_news_news_id (news_id),
  KEY ix_market_news_news_id (news_id),
  KEY ix_market_news_title (title),
  KEY ix_market_news_source (source),
  KEY ix_market_news_news_type (news_type),
  KEY ix_market_news_published_at (published_at),
  KEY ix_market_news_fetched_at (fetched_at),
  KEY ix_market_news_sentiment (sentiment),
  KEY ix_market_news_type_published (news_type, published_at),
  KEY ix_market_news_source_published (source, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='市场新闻公告资讯表';

CREATE TABLE IF NOT EXISTS stock_features (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  symbol VARCHAR(32) NOT NULL COMMENT '股票代码',
  period VARCHAR(32) NOT NULL COMMENT '特征周期，例如 daily',
  trade_time VARCHAR(64) NOT NULL COMMENT '交易日期或交易时间',
  `close` DOUBLE NULL COMMENT '收盘价',
  ma5 DOUBLE NULL COMMENT '5 周期均线',
  ma10 DOUBLE NULL COMMENT '10 周期均线',
  ma20 DOUBLE NULL COMMENT '20 周期均线',
  ma60 DOUBLE NULL COMMENT '60 周期均线',
  return_1 DOUBLE NULL COMMENT '1 周期涨跌幅',
  return_5 DOUBLE NULL COMMENT '5 周期涨跌幅',
  return_20 DOUBLE NULL COMMENT '20 周期涨跌幅',
  volatility_20 DOUBLE NULL COMMENT '20 周期波动率',
  volume_ratio_5 DOUBLE NULL COMMENT '5 周期成交量比',
  price_position_20 DOUBLE NULL COMMENT '20 周期价格位置',
  price_position_60 DOUBLE NULL COMMENT '60 周期价格位置',
  trend_direction VARCHAR(64) NULL COMMENT '趋势方向',
  trend_score DOUBLE NULL COMMENT '趋势分数',
  `signal` VARCHAR(64) NULL COMMENT '交易信号',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  UNIQUE KEY uq_stock_feature (symbol, period, trade_time),
  KEY idx_stock_features_symbol (symbol),
  KEY idx_stock_features_period (period),
  KEY idx_stock_features_trade_time (trade_time),
  KEY idx_stock_features_symbol_period (symbol, period),
  KEY idx_stock_features_symbol_period_time (symbol, period, trade_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='股票基础特征表';

CREATE TABLE IF NOT EXISTS paper_accounts (
  account_id VARCHAR(64) NOT NULL COMMENT '模拟账户 ID',
  initial_cash DOUBLE NOT NULL COMMENT '初始资金',
  cash DOUBLE NOT NULL COMMENT '当前现金',
  realized_pnl DOUBLE NOT NULL DEFAULT 0 COMMENT '已实现盈亏',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模拟账户表';

CREATE TABLE IF NOT EXISTS paper_positions (
  symbol VARCHAR(32) NOT NULL COMMENT '股票代码',
  quantity INT NOT NULL COMMENT '持仓数量',
  avg_price DOUBLE NOT NULL COMMENT '平均持仓成本',
  opened_at VARCHAR(64) NOT NULL COMMENT '开仓时间 ISO 字符串',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模拟当前持仓表';

CREATE TABLE IF NOT EXISTS paper_orders (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  order_id VARCHAR(128) NOT NULL COMMENT '模拟订单 ID',
  symbol VARCHAR(32) NOT NULL COMMENT '股票代码',
  side VARCHAR(16) NOT NULL COMMENT '方向 buy/sell',
  quantity INT NOT NULL COMMENT '成交数量',
  price DOUBLE NOT NULL COMMENT '成交价格',
  amount DOUBLE NOT NULL COMMENT '净现金成交额：买入=毛成交额+费用，卖出=毛成交额-费用，不是毛成交额',
  status VARCHAR(32) NOT NULL COMMENT '订单状态 filled/rejected',
  reason TEXT NULL COMMENT '拒绝原因或说明',
  strategy_mode VARCHAR(32) NULL COMMENT '策略模式 manual/strict/normal/loose；manual 表示手动交易',
  decision_json LONGTEXT NULL COMMENT '策略决策快照 JSON',
  requested_price DOUBLE NULL COMMENT '请求价格/原始下单价格',
  gross_amount DOUBLE NULL COMMENT '毛成交金额（未扣费用前）',
  commission DOUBLE NULL COMMENT '佣金',
  stamp_duty DOUBLE NULL COMMENT '印花税',
  transfer_fee DOUBLE NULL COMMENT '过户费',
  total_fee DOUBLE NULL COMMENT '总交易费用',
  realized_pnl DOUBLE NULL COMMENT '已实现盈亏（仅卖出/平仓订单，卖出净回款-对应持仓成本）',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  UNIQUE KEY uq_paper_orders_order_id (order_id),
  KEY idx_paper_orders_symbol (symbol),
  KEY idx_paper_orders_symbol_created (symbol, created_at),
  KEY idx_paper_orders_status (status),
  KEY idx_paper_orders_strategy_mode (strategy_mode),
  KEY ix_paper_orders_symbol_strategy_status_created (symbol, strategy_mode, status, created_at),
  KEY ix_paper_orders_strategy_status_created (strategy_mode, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模拟订单记录表';

CREATE TABLE IF NOT EXISTS paper_cash_flows (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  order_id VARCHAR(128) NULL COMMENT '关联模拟订单 ID',
  symbol VARCHAR(32) NULL COMMENT '股票代码',
  side VARCHAR(16) NOT NULL COMMENT '资金方向 buy/sell/reset',
  amount DOUBLE NOT NULL COMMENT '资金变动金额，买入为负，卖出为正',
  cash_after DOUBLE NOT NULL COMMENT '变动后现金余额',
  note TEXT NULL COMMENT '流水说明',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  KEY idx_paper_cash_flows_order_id (order_id),
  KEY idx_paper_cash_flows_symbol (symbol),
  KEY idx_paper_cash_flows_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模拟资金流水表';

CREATE TABLE IF NOT EXISTS backtest_runs (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  run_id VARCHAR(128) NOT NULL COMMENT '回测运行唯一 ID',
  scope VARCHAR(32) NOT NULL COMMENT '回测范围 symbol/pool',
  symbol VARCHAR(32) NULL COMMENT '股票代码（单股回测）',
  pool_code VARCHAR(64) NULL COMMENT '股票池代码（股票池回测）',
  period VARCHAR(32) NOT NULL COMMENT '回测周期，例如 daily',
  strategy_mode VARCHAR(32) NOT NULL COMMENT '策略模式 strict/normal/loose',
  status VARCHAR(32) NOT NULL COMMENT '回测状态 ok/insufficient_data',
  start_date VARCHAR(32) NULL COMMENT '回测开始日期',
  end_date VARCHAR(32) NULL COMMENT '回测结束日期',
  initial_cash DOUBLE NULL COMMENT '初始资金',
  quantity INT NULL COMMENT '每笔数量',
  rows_count INT NULL COMMENT '原始 K 线总行数',
  tested_bars INT NULL COMMENT '实际参与回测的 bar 数量',
  trade_count INT NULL COMMENT '交易次数',
  round_trip_count INT NULL COMMENT '完整买卖回合数',
  total_pnl DOUBLE NULL COMMENT '总盈亏',
  total_pnl_pct DOUBLE NULL COMMENT '总收益率',
  final_equity DOUBLE NULL COMMENT '最终权益',
  max_drawdown DOUBLE NULL COMMENT '最大回撤',
  win_rate DOUBLE NULL COMMENT '胜率',
  summary_json LONGTEXT NULL COMMENT '回测结果摘要 JSON',
  params_json LONGTEXT NULL COMMENT '回测参数 JSON',
  rule_json LONGTEXT NULL COMMENT '策略规则 JSON',
  execution_rules_json LONGTEXT NULL COMMENT '成交费用/执行规则 JSON',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  UNIQUE KEY uq_backtest_runs_run_id (run_id),
  KEY ix_backtest_runs_run_id (run_id),
  KEY ix_backtest_runs_scope (scope),
  KEY ix_backtest_runs_symbol (symbol),
  KEY ix_backtest_runs_pool_code (pool_code),
  KEY ix_backtest_runs_period (period),
  KEY ix_backtest_runs_strategy_mode (strategy_mode),
  KEY ix_backtest_runs_status (status),
  KEY ix_backtest_runs_scope_status_strategy_created (scope, status, strategy_mode, created_at),
  KEY ix_backtest_runs_symbol_status_created (symbol, status, created_at),
  KEY ix_backtest_runs_pool_status_created (pool_code, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='回测运行汇总表';

CREATE TABLE IF NOT EXISTS backtest_trades (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  run_id VARCHAR(128) NOT NULL COMMENT '关联回测运行 ID',
  symbol VARCHAR(32) NOT NULL COMMENT '股票代码',
  period VARCHAR(32) NOT NULL COMMENT '回测周期',
  trade_time VARCHAR(64) NOT NULL COMMENT '成交时间/信号触发时间',
  side VARCHAR(16) NOT NULL COMMENT '交易方向 buy/sell',
  accepted TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否成交成功',
  quantity INT NULL COMMENT '成交数量',
  price DOUBLE NULL COMMENT '实际成交价格',
  requested_price DOUBLE NULL COMMENT '请求价格/原始下单价格',
  amount DOUBLE NULL COMMENT '实际成交金额',
  total_fee DOUBLE NULL COMMENT '本次交易总费用',
  realized_pnl DOUBLE NULL COMMENT '已实现盈亏（通常卖出时有值）',
  reason TEXT NULL COMMENT '成交/拒绝原因说明',
  payload_json LONGTEXT NULL COMMENT '回测交易扩展明细 JSON',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  KEY ix_backtest_trades_run_id (run_id),
  KEY ix_backtest_trades_symbol (symbol),
  KEY ix_backtest_trades_trade_time (trade_time),
  KEY ix_backtest_trades_side (side)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='回测成交明细表';

CREATE TABLE IF NOT EXISTS backtest_equity_curve (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  run_id VARCHAR(128) NOT NULL COMMENT '关联回测运行 ID',
  symbol VARCHAR(32) NOT NULL COMMENT '股票代码',
  period VARCHAR(32) NOT NULL COMMENT '回测周期',
  trade_time VARCHAR(64) NOT NULL COMMENT '权益时间点',
  cash DOUBLE NULL COMMENT '当时现金余额',
  market_value DOUBLE NULL COMMENT '当时持仓市值',
  equity DOUBLE NULL COMMENT '当时总权益（现金+持仓）',
  realized_pnl DOUBLE NULL COMMENT '当时累计已实现盈亏',
  unrealized_pnl DOUBLE NULL COMMENT '当时浮动盈亏',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  KEY ix_backtest_equity_curve_run_id (run_id),
  KEY ix_backtest_equity_curve_symbol (symbol),
  KEY ix_backtest_equity_curve_trade_time (trade_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='回测权益曲线表';

CREATE TABLE IF NOT EXISTS task_execution_records (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  execution_id VARCHAR(128) NOT NULL COMMENT '任务执行唯一 ID',
  task_name VARCHAR(128) NOT NULL COMMENT '任务名称',
  task_type VARCHAR(64) NOT NULL COMMENT '任务类型 data_sync/feature_compute/auto_trade',
  trigger_type VARCHAR(64) NOT NULL COMMENT '触发方式 manual_api/scheduler',
  status VARCHAR(32) NOT NULL COMMENT '执行状态 running/success/failed',
  started_at VARCHAR(64) NOT NULL COMMENT '开始时间 ISO 字符串',
  finished_at VARCHAR(64) NULL COMMENT '结束时间 ISO 字符串',
  duration_ms DOUBLE NULL COMMENT '执行耗时（毫秒）',
  params_json LONGTEXT NULL COMMENT '任务入参 JSON',
  result_summary_json LONGTEXT NULL COMMENT '结果摘要 JSON',
  error_message LONGTEXT NULL COMMENT '错误信息或异常摘要',
  candidate_count INT NULL COMMENT '候选数量',
  success_count INT NULL COMMENT '成功数量',
  failed_count INT NULL COMMENT '失败数量',
  accepted_count INT NULL COMMENT '接受/执行数量',
  rejected_count INT NULL COMMENT '拒绝数量',
  order_count INT NULL COMMENT '订单数量',
  created_at VARCHAR(64) NOT NULL COMMENT '创建时间 ISO 字符串',
  updated_at VARCHAR(64) NOT NULL COMMENT '更新时间 ISO 字符串',
  created_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '创建人',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'system' COMMENT '更新人',
  PRIMARY KEY (id),
  UNIQUE KEY uq_task_execution_records_execution_id (execution_id),
  KEY ix_task_execution_records_execution_id (execution_id),
  KEY ix_task_execution_records_task_name (task_name),
  KEY ix_task_execution_records_task_type (task_type),
  KEY ix_task_execution_records_trigger_type (trigger_type),
  KEY ix_task_execution_records_status (status),
  KEY ix_task_execution_records_started_at (started_at),
  KEY ix_task_execution_records_finished_at (finished_at),
  KEY ix_task_execution_records_task_status_started (task_name, status, started_at),
  KEY ix_task_execution_records_type_status_started (task_type, status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务执行记录表';

INSERT INTO paper_accounts (account_id, initial_cash, cash, realized_pnl, created_at, updated_at, created_by, updated_by)
VALUES ('default', 1000000, 1000000, 0, NOW(), NOW(), 'system', 'system')
ON DUPLICATE KEY UPDATE account_id = account_id;
